version: 2
updates:
  - package-ecosystem: gradle
    directory: /enterprise-fashion-ecommerce/backend
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
